// Generates environment.ts and environment.prod.ts from environment variables.
// Locally: reads from .env via dotenv.
// Vercel / CI: reads from the platform's environment variables directly.
const { writeFileSync, mkdirSync } = require('fs');
const { resolve, dirname } = require('path');

// Load .env for local development (no-op in Vercel — vars already in process.env)
try {
  require('dotenv').config();
} catch {
  // dotenv not installed or .env missing — rely on process.env
}

const { SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY } = process.env;

const missing = [];
if (!SUPABASE_URL)              missing.push('SUPABASE_URL');
if (!SUPABASE_ANON_KEY)         missing.push('SUPABASE_ANON_KEY');
if (!SUPABASE_SERVICE_ROLE_KEY) missing.push('SUPABASE_SERVICE_ROLE_KEY');

if (missing.length) {
  console.error('❌  Missing environment variables:', missing.join(', '));
  console.error('    Create a .env file based on .env.example');
  process.exit(1);
}

const content = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  supabaseUrl: '${SUPABASE_URL}',
  supabaseAnonKey: '${SUPABASE_ANON_KEY}',
  supabaseServiceRoleKey: '${SUPABASE_SERVICE_ROLE_KEY}',
};
`;

const targets = [
  resolve(__dirname, '../src/environments/environment.ts'),
  resolve(__dirname, '../src/environments/environment.prod.ts'),
];

targets.forEach(path => {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  console.log('✅  Written:', path);
});
